# name of workflow process
name: CI/CD

# when to run the workflow - on push to main branch
on:
  push:
    branches: [main]
# jobs to be carried out
jobs:
  # run a build job
  # 2 parts environment - runs-on & strategy
  build:
    # os rqd
    runs-on: ubuntu-latest
    # env to be installed
    strategy:
      matrix:
        node-version: [19.x]

    # workflow steps
    steps:
      # github knows the secrets
      - name: Checkout repository
        uses: actions/checkout@v3

      # setup Node -v from strat matrix
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: ${{ matrix.node-version }}

      # install dependencies
      - name: Install dependencies
        run: npm install

      # login to docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # setup docker build
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # create build and push to Docker hub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mod10-mvc-demo:latest

      # output digest to show build was successful
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
